### ISSUE TITLE
Increase session duration

### ISSUE THREAD

**Issue by c-dilks** [JeffersonLab/btm#11]
Hall B shift takers are required to fill out the BTM timesheet every hour at the top of the hour, and they typically don't touch the timesheet any other time; since the user session duration is less than an hour, the typical shift taker must log in eight times during a typical 8 hour shift, unless they routinely interact with the BTM webpage (_e.g._, refreshing it).

It would be ideal if the shift taker only has to log in once per shift; logging in can be distracting from more critical shift responsibilities, especially if the user's password is difficult to type.

Related: https://github.com/JeffersonLab/smoothness/issues/15

**Comment by slominskir** [comment]
Please check with hall staff to ensure there isn’t a script / browser plug-in clearing your browser session / cache every hour.  My understanding is there was something to that effect setup on your hall kiosk computer.   I don’t believe the other two hall counting houses are having this issue.  The app session expiration is already configured at 8 hours so it seems something client side is clearing it.

**Comment by slominskir** [comment]
Note: closing your web browser also clears your session.

**Comment by sawjlab** [comment]
Constantly having to login to the bta system is an issue in Hall C as well.

Tabs in the same browser logged into the logbook stay logged in at least for the duration of a shift.

**Comment by baltzell** [comment]
> Please check with hall staff to ensure there isn’t a script / browser plug-in clearing your browser session / cache every hour. My understanding is there was something to that effect setup on your hall kiosk computer. I don’t believe the other two hall counting houses are having this issue. The app session expiration is already configured at 8 hours so it seems something client side is clearing it.

I remember someone acting like they had done that in Hall B, made some script or setting/plugin mess on some particular browser instance, which would be a weird approach anyway since we run per-machine profiles, but I suspect that was just misinformation and I found no evidence of it on Hall B computers.  Regardless, I tested in 100% stock firefox and google-chrome profiles on rhel7, rhel8, and rhel9, and saw similar behavior in all combinations at least once, automatic logout on the hour.

**Comment by slominskir** [comment]
Is this a group account or personal account being logged out?   Is there more than one instance logged in somewhere else using the account in question?

There is an hourly automatic refresh (if the edit form is not open) so one wild guess at this point is that could be problematic.  Keep the last row on the table in edit mode as a test to avoid the hourly auto refresh and see if that fixes it.   

Another thing I can try later is I think the OAuth session is only 30 minutes, but that should be separate from the app session - that's something I can bump up if it turns out to be related but historically I don't think it was.

**Comment by c-dilks** [comment]
> Is this a group account or personal account being logged out?

Personal

> Is there more than one instance logged in somewhere else using the account in question?

No other instances with my user name.

> Another thing I can try later is I think the OAuth session is only 30 minutes

When I was on shift, it seemed to be longer than ~15 min., but shorter than ~30 min; I wasn't timing it very precisely, so it could very well be exactly 30 min.

**Comment by slominskir** [comment]
I was able to recreate the issue.  I left browser open for an hour and on auto-refresh was logged out.  Error in app server log is:
```
ELY23012: Refresh token failure status: 400 {"error":"invalid_grant","error_description":"Token is not active"}
```

I've bumped up the Keycloak SSO Session timeout from 30 minutes to 8 hours.   This appears to fix the issue.    Waiting another hour and on auto-refresh all is well (still logged in).

The client adapter used in the app server changed over the summer with the patching/upgrades and it appears the new "Elytron" OAuth client lib uses token refreshes to maintain the app server session in sync with OAuth session.  The app server session and Keycloak OAuth session are distinct and I don't think the prior lib did this sync (backchannel logout on session expiration - it's probably configurable - we'll just bump SSO expiration for now).  The app server session is set to 8 hours (480 minutes) as seen here:

https://github.com/JeffersonLab/btm/blob/ad0b3f413db554cd96f3b40eac4ca1626d8cb68d/src/main/webapp/WEB-INF/web.xml#L45

Ironically this issue is nearly the opposite of https://github.com/JeffersonLab/smoothness/issues/16 in which users could not log out.  In this issue users can't stay logged in.   There are up to three different sessions/cookies in play: Wildfly app server, Keycloak OAuth server, and formally CUE login was handled by MIS Shibboleth, which has it's own session.

**Comment by baltzell** [comment]
> Is this a group account or personal account being logged out? Is there more than one instance logged in somewhere else using the account in question?

That google-chrome/firefox+rhel7/8/9 test was with my personal account, after scratching all the relevant web browser profiles in $HOME and letting google-chrome/firefox create one from scratch with whatever their defaults are.

**Comment by slominskir** [comment]
This should be resolved.   If not, let me know.
